#!/usr/bin/env php
<?php
/**
 * Proctor CLI
 */

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once(__DIR__ . '/vendor/autoload.php');
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    echo "Dependencies not found. Please run composer install.";
    exit(1);
}

use Symfony\Component\Console\Application;

$app = new Application('Proctor', Proctor\Proctor::VERSION);
$app->add(new Proctor\Command\ConfigInit('config:init'));
$app->add(new Proctor\Command\SetupDrupal('setup:drupal'));
$app->add(new Proctor\Command\SetupCircle('setup:circle'));
$app->add(new Proctor\Command\Build('build'));
$app->add(new Proctor\Command\UseSite('use'));
$app->add(new Proctor\Command\Run('run'));
$app->add(new Proctor\Command\Prepare('prepare'));
$app->run();
